PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obt: <https://w3id.org/ns/ontoboldt#>
PREFIX eng: <https://w3id.org/ontoboldt/ns/engineering-vocabulary#>
PREFIX p-plan: <http://purl.org/net/p-plan#>

SELECT 
    ?output 
    ?type
    (group_concat(?stepName) as ?name)
WHERE {
    ?step p-plan:hasOutputVar ?output ;
        a ?type ;
        ?rdfs:label ?stepName .
}
GROUP BY ?output ?type
HAVING(COUNT(?step) > 1)
